language: python
python:
  - "2.7"
install:
  - pip install nose
  - pip install lxml
  - pip install pyyaml
  - pip install appengine-sdk
  - pip install flake8
script:
  - flake8 *.py */*.py
  - python tests.py
