application: codeforces-mn
version: new

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(favicon\.ico)
  static_files: static/\1
  upload: static/.*

- url: /images
  static_dir: images
  expiration: "7d"

- url: /static
  static_dir: static
  expiration: "7d"

- url: /update
  script: app.app
  login: admin

- url: /setup
  script: app.app
  login: admin

- url: /ratings/update
  script: app.app
  login: admin

- url: /.*
  script: app.app

libraries:
- { name: webapp2,    version: "2.5.2" }
- { name: jinja2,     version: "2.6"   }
- { name: markupsafe, version: "0.15"  } # required for jinja2
- { name: django,     version: "1.3"   }
- { name: lxml,       version: "2.3"   }

skip_files:
- ^(app|index)\.y(a)?ml         # appengine config files
- ^(.*/)?.*\.(styl|coffee)$     # stylus, coffeescript files
- ^(.*/)?(#.*#)|(.*~)           # editor temp files
- ^(.*/)?.*\.py[co]             # environment temp files
- ^(.*/)?\..*$                  # dot-prefixed files
