application: codeforces-mn
version: live

runtime: python27
api_version: 1
threadsafe: true
# Expires: 2016-05-19 renew ssl certificate

handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/.*

- url: /images
  static_dir: images
  expiration: "7d"

- url: /static
  static_dir: static
  expiration: "7d"

- url: /update
  script: app.app
  login: admin

- url: /update-comments
  script: app.app
  login: admin

- url: /setup
  script: app.app
  login: admin

- url: /ratings/update-codeforces
  script: app.app
  login: admin

- url: /ratings/update-topcoder
  script: app.app
  login: admin

- url: /.*
  script: app.app

libraries:
- { name: jinja2,     version: "2.6"   }
- { name: markupsafe, version: "0.15"  } # required for jinja2
- { name: lxml,       version: "2.3"   }

skip_files:
- ^(.*/)?\..*$         # Dot-prefixed unix hidden files
- ^(.*/)?(#.*#)|(.*~)  # Editor temp files
- ^(.*/)?.*\.py[co]    # Environment temp files
- ^(.*/)?.*\.styl$     # CSS sources
- ^(.*/)?.*\.coffee$   # JS sources
