// Generated by CoffeeScript 1.9.3
var STYLE, VERSION, box_html, row_tmpl, translate;

String.prototype.start_with = function(str) {
  return this.substr(0, str.length) === str;
};

String.prototype.end_with = function(str) {
  return this.slice(-str.length) === str;
};

String.prototype.contain = function(str) {
  return this.indexOf(str) > -1;
};

String.prototype.is_numeric = function() {
  return !isNaN(parseFloat(this)) && isFinite(this);
};

VERSION = "0.2.5";

STYLE = "<style>\n  .mn-please a          { font-weight:bold; cursor:pointer }\n  .mn-statement ul      { margin-bottom:1em }\n  .mn-statement .credit { text-align:right; font-style:italic }\n  .sample-tests .title  { font-family:sans-serif !important;\n                          font-size:1em !important;\n                          text-transform:none !important }\n</style>";

$(function() {
  return $("#header .lang-chooser > div:first").prepend("<a href=\"http://codeforces.mn/\">\n  <img src=\"http://codeforces.mn/images/flag-mn.png\" title=\"Монголоор\">\n</a>");
});

$.get("http://codeforces.mn/extension?" + VERSION, function(text) {
  var c, i, j, k, l, len, len1, len2, ready, ref, ref1, ref2, storage, t, total;
  storage = {};
  ref = text.split("\n")[0].split("|");
  for (j = 0, len = ref.length; j < len; j++) {
    i = ref[j];
    storage["problem:" + i] = 1;
  }
  ref1 = text.split("\n")[1].split("|");
  for (k = 0, len1 = ref1.length; k < len1; k++) {
    c = ref1[k];
    i = c.split(":")[0];
    ready = Number(c.split(":")[1].split("/")[0]);
    total = Number(c.split(":")[1].split("/")[1]);
    storage["contest:" + i] = {
      ready: ready,
      total: total
    };
  }
  storage.credits = [];
  ref2 = text.split("\n")[2].split("|");
  for (l = 0, len2 = ref2.length; l < len2; l++) {
    t = ref2[l];
    storage.credits.push(t.split(":"));
  }
  storage.total = text.split("\n")[3];
  return localStorage.mn = JSON.stringify(storage);
});

if (location.pathname === "/") {
  box_html = "<div class=\"roundbox sidebox top-contributed top-translators\">\n  <div class=\"roundbox-lt\">&nbsp;</div>\n  <div class=\"roundbox-rt\">&nbsp;</div>\n  <div class=\"caption titled\">→ Top translators</div>\n  <table class=\"rtable \">\n    <tr>\n      <th class=\"left\" style=\"width:2.25em\">#</th>\n      <th>User</th>\n      <th style=\"font-size:13px\">{ready}/{total}</th>\n    </tr>\n    {content}\n  </table>\n</div>";
  row_tmpl = "<tr style=\"display:{display}\" class=\"{class}\">\n  <td class=\"left\">{place}</td>\n  <td>{name}</td>\n  <td>{score}</td>\n</tr>";
  $(function() {
    var colorful, content, j, len, name, place, ready, ref, ref1, row_html, score, storage;
    $("head").append("<style>\n  .top-translators table tr:last-child td {\n    border-bottom: none\n  }\n  .top-translators .bottom-links {\n    background: #f5f5f5;\n    border-left: none !important;\n    font-size: 11px !important;\n    text-align: right !important\n  }\n</style>");
    storage = JSON.parse(localStorage.mn || "{}");
    colorful = function(name, score) {
      var color;
      score = Number(score);
      if (score >= 0) {
        color = "gray";
      }
      if (score >= 25) {
        color = "green";
      }
      if (score >= 50) {
        color = "blue";
      }
      if (score >= 75) {
        color = "orange";
      }
      if (score >= 100) {
        color = "red";
      }
      return "<a class=\"rated-user user-" + color + "\">" + name + "</a>";
    };
    if (storage.credits) {
      content = "";
      ready = 0;
      ref = storage.credits;
      for (place = j = 0, len = ref.length; j < len; place = ++j) {
        ref1 = ref[place], name = ref1[0], score = ref1[1];
        row_html = row_tmpl.replace("{place}", place + 1);
        row_html = row_html.replace("{name}", colorful(name, score));
        row_html = row_html.replace("{score}", score);
        if (place % 2 === 0) {
          row_html = row_html.replace("{class}", "dark");
        } else {
          row_html = row_html.replace("{class}", "");
        }
        if (place >= 10) {
          row_html = row_html.replace("{display}", "none");
        } else {
          row_html = row_html.replace("{display}", "table-row");
        }
        content += row_html;
        ready += Number(score);
      }
      content += "<tr>\n  <td class=\"bottom-links\" colspan=\"3\">\n    <a href=\"javascript:;\" class=\"js-more\">View all &rarr;</a>\n  </td>\n</tr>";
      box_html = box_html.replace("{ready}", ready);
      box_html = box_html.replace("{total}", storage.total);
      box_html = box_html.replace("{content}", content);
      $("#sidebar .top-contributed:first").before(box_html);
      return $(".top-translators .js-more").on("click", function() {
        $(this).closest("table").find("tr").show();
        return $(this).closest("tr").fadeOut().remove();
      });
    }
  });
}

if (location.pathname.match(/\/problemset(?!\/problem\/)/)) {
  $(function() {
    var storage;
    $("head").append("<style>\n  .problems tr td:nth-child(2) > div:first-child {\n    margin-left: 14px\n  }\n  .problems .mn td:nth-child(2) > div:first-child {\n    margin-left: 0\n  }\n  .problems .mn td:nth-child(2) > div:first-child a:before {\n    content: \"✱ \";\n    color: #c900a9;\n    display: inline-block;\n    float: left;\n    margin-right: 4px;\n    text-decoration: none\n  }\n</style>");
    storage = JSON.parse(localStorage.mn || "{}");
    return $(".problems tr").each(function() {
      var problem_id;
      problem_id = $(this).find("td.id").text().trim().replace(/(\d+)/, "$1-");
      if (storage["problem:" + problem_id]) {
        return $(this).addClass("mn");
      }
    });
  });
}

if (location.pathname.match(/\/problemset\/problem\//)) {
  $(function() {
    var problem_id, storage;
    $("head").append(STYLE);
    storage = JSON.parse(localStorage.mn || "{}");
    problem_id = location.pathname.replace("/problemset/problem/", "");
    problem_id = problem_id.replace("/", "-").toUpperCase();
    if (storage["problem:" + problem_id]) {
      $(".problem-statement .header .title").after("<div class=\"mn-please\"><a>Монголоор унших</a></div>");
    }
    return $(".mn-please a").on("click", translate);
  });
}

if (location.pathname.start_with("/contests")) {
  $(function() {
    var storage;
    $("head").append("<style>\n  .mn      { font-size:0.9em; color:#666666 }\n  .mn-full { font-size:0.9em; color:#c900a9; font-weight:bold }\n</style>");
    storage = JSON.parse(localStorage.mn || "{}");
    return $(".contests-table tr td:nth-child(1)").each(function() {
      var contest_id, ready, ref, ref1, span, total;
      $(this).find("a")[0].innerHTML = "Enter";
      if ($(this).find("a").length === 2) {
        $(this).find("a:first").next()[0].outerHTML = "<span>&middot;</span> ";
        $(this).find("a")[1].innerHTML = "Virtual participation";
      } else {
        $(this).closest("tr").hide();
      }
      contest_id = $(this).find("a:first").attr("href").replace("/contest/", "");
      while (contest_id.length < 3) {
        contest_id = "0" + contest_id;
      }
      ready = ((ref = storage["contest:" + contest_id]) != null ? ref.ready : void 0) || 0;
      total = ((ref1 = storage["contest:" + contest_id]) != null ? ref1.total : void 0) || 0;
      if (ready <= 0) {
        return;
      }
      span = ready === total ? "mn-full" : "mn";
      return $(this).append("<span class=\"" + span + "\">Орчуулагдсан: " + ready + " / " + total + "</span>");
    });
  });
}

if (location.pathname.match(/^\/contest\/\d+\/?$/)) {
  $(function() {
    var storage;
    $("head").append("<style>\n  .problems tr td:nth-child(2) > div:first-child {\n    margin-left: 14px\n  }\n  .problems .mn td:nth-child(2) > div:first-child {\n    margin-left: 0\n  }\n  .problems .mn td:nth-child(2) > div:first-child a:before {\n    content: \"✱ \";\n    color: #c900a9;\n    display: inline-block;\n    float: left;\n    margin-right: 4px;\n    text-decoration: none\n  }\n</style>");
    storage = JSON.parse(localStorage.mn || "{}");
    return $(".problems tr").each(function() {
      var problem_id;
      problem_id = location.pathname.replace("/contest/", "").replace("/", "");
      problem_id = problem_id + "-" + $(this).find("td.id").text().trim();
      if (storage["problem:" + problem_id]) {
        return $(this).addClass("mn");
      }
    });
  });
}

if (location.pathname.match(/^\/contest\/\d+\/problem\//)) {
  $(function() {
    var problem_id, storage;
    $("head").append(STYLE);
    storage = JSON.parse(localStorage.mn || "{}");
    problem_id = location.pathname.replace("/contest/", "");
    problem_id = problem_id.replace("/problem/", "-").toUpperCase();
    if (storage["problem:" + problem_id]) {
      $(".problem-statement .header .title").after("<div class=\"mn-please\"><a>Монголоор унших</a></div>");
    }
    return $(".mn-please a").on("click", translate);
  });
}

translate = function() {
  var problem_id;
  if (location.pathname.start_with("/problemset/problem/")) {
    problem_id = location.pathname.replace("/problemset/problem/", "");
    problem_id = problem_id.replace("/", "-").toUpperCase();
  }
  if (location.pathname.start_with("/contest/")) {
    problem_id = location.pathname.replace("/contest/", "");
    problem_id = problem_id.replace("/problem/", "-").toUpperCase();
  }
  $(".mn-please").fadeOut("fast", function() {
    return $(this).html("<strong>Орчуулж байна...</strong>").fadeIn("fast");
  });
  return $.get("http://codeforces.mn/extension/" + problem_id + ".html?" + VERSION, function(r) {
    var $r, body, curr, script;
    $(".problem-statement").addClass("mn-statement");
    $r = $("<div/>").html(r);
    $(".header .title").html((problem_id.slice(-1)) + ". " + ($r.find("h1").html()));
    body = [];
    curr = $r.find("h1").next();
    while (curr[0] && curr[0].tagName !== "H3") {
      body.push(curr[0].outerHTML);
      curr = curr.next();
    }
    $(".header").next().html(body.join("\n"));
    body = [];
    curr = $r.find("h3").next();
    while (curr[0] && curr[0].tagName !== "H3") {
      body.push(curr[0].outerHTML);
      curr = curr.next();
    }
    $(".input-specification").html("<div class=\"section-title\">Оролт</div>\n" + (body.join("\n")));
    body = [];
    curr = $r.find("h3:eq(1)").next();
    while (curr[0] && curr[0].tagName !== "H3") {
      body.push(curr[0].outerHTML);
      curr = curr.next();
    }
    $(".output-specification").html("<div class=\"section-title\">Гаралт</div>\n" + (body.join("\n")));
    $(".sample-tests .section-title").html("Жишээ тэстүүд");
    $(".sample-tests .section-title").html("Жишээ тэстүүд");
    $(".sample-tests .sample-test .input .title").html("Оролт");
    $(".sample-tests .sample-test .output .title").html("Гаралт");
    if ($r.find("h3:eq(2)").length) {
      body = [];
      curr = $r.find("h3:eq(2)").next();
      while (curr[0] && curr[0].tagName !== "H3") {
        body.push(curr[0].outerHTML);
        curr = curr.next();
      }
      $(".problem-statement .note").html("<div class=\"section-title\">Тэмдэглэл</div>\n" + (body.join("\n")));
    }
    $(".mn-please").fadeOut("fast");
    script = document.createElement("script");
    script.type = "text/x-mathjax-config";
    script.text = "MathJax.Hub.Config({\n  tex2jax: {\n    inlineMath: [[\"$\", \"$\"]],\n    displayMath: [[\"$$\", \"$$\"]]\n  },\n  TeX: {\n    extensions: [\n      \"AMSmath.js\",\n      \"AMSsymbols.js\",\n      \"noErrors.js\"\n    ]\n  },\n  jax: [\"input/TeX\", \"output/HTML-CSS\"],\n  extensions: [\"tex2jax.js\"],\n  showMathMenu: false\n});";
    document.head.appendChild(script);
    script = document.createElement("script");
    script.type = "text/javascript";
    script.src = "//cdn.mathjax.org/mathjax/latest/MathJax.js";
    return document.head.appendChild(script);
  });
};
